apiVersion: integration/v1
kind: Step
name: deploy
version: 4
summary: Deploy a Helm chart
description: This step deploys a Helm chart to a Kubernetes cluster.
icon:
build:
  apiVersion: build/v1
  kind: Docker
publish:
  repository: relaysh/helm-step-deploy
examples:
- summary: Deploy a helm chart for 'my-app' from a local chart repository
  content:
    apiVersion: v1 
    kind: Step
    name: helm-deployer
    image: relaysh/helm-step-deploy
    spec:
      credentials:
        ca.pem: !Secret ca
        key.pem: !Secret key
        cert.pem: !Secret cert
      values:
        api:
          image:
            tag: !Secret api.image.tag
          adminToken:
            secretRef:
              name: admin-token
          sendGrid:
            secretRef:
              name: sendgrid-ref
          googleCredentials:
            secretRef:
              name: google-creds
          storage:
            address: gs://storage
      chart: !Parameter chart
      namespace: !Parameter namespace 
      recreatePods: true
      git: 
        ssh_key: !Secret ssh_key
        known_hosts: !Secret known_hosts
        name: !Parameter my-repo
        branch: !Parameter branch 
        repository: !Parameter repo-path     
      cluster:
        name: my-cluster
        connection: !Connection { type: kubernetes, name: my-cluster }

schemas:
  spec:
    source: file
    file: spec.schema.json
