apiVersion: integration/v1
kind: Step
name: deploy
version: 4
summary: Deploy a Helm chart
description: This step deploys a Helm chart to a Kubernetes cluster.
icon:
build:
  apiVersion: build/v1
  kind: Docker
publish:
  repository: relaysh/helm-step-deploy
examples:
- summary: Deploy the Puppetboard web interface to PuppetDB
  content:
    apiVersion: v1
    kind: Step
    name: deploy
    image: relaysh/helm-step-deploy
    spec:
      cluster:
        name: my-cluster
        connection: !Connection {type: kubernetes, name: my-k8s-cluster}
      name: !Parameter releaseName
      namespace: !Parameter releaseNamespace
      repository: https://charts.boo.tc
      chart: puppetboard
      values:
        puppetDbHost: !Parameter puppetDBHost

schemas:
  spec:
    source: file
    file: spec.schema.json
